apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    group: {{ .Values.group }}
  name: jenkins-create-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    group: {{ .Values.group }}
  name: jenkins-create-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-create-secrets
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: {{ .Release.Namespace }}